enum ModalType {
  CHANGE_INFOMATION = 'CHANGE_INFOMATION',
  CONFIRM_EXIT = 'CONFIRM_EXIT',
  CONFIRM_SIGNOUT = 'CONFIRM_SIGNOUT',
  CONFIRM_DELETE = 'CONFIRM_DELETE',
  IMAGE_OPTION = 'IMAGE_OPTION',
  LOADING = 'LOADING',
}

export { ModalType };
